-- CREATE DATABASE IF NOT EXIST
CREATE DATABASE IF NOT EXIST houseguard;

-- SELECT THE DATABASE
use houseguard;


--TABLE USERS
CREATE TABLE IF NOT EXISTS USER(ID int primary key, USER_NAME VARCHAR(100), DATE_REGISTERED DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
					

-- TABLE PROBE_REQUEST
CREATE TABLE IF NOT EXISTS PROBE_REQUEST( ID int primary key, MACADDRESS VARCHAR(20), LOGGED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,USER_ID int, FOREIGN KEY (USER_ID) REFERENCES USER(id));
					
					
					
-- TABLE ALERTS
CREATE TABLE IF NOT EXISTS ALERT( ID int primary key, MACADDRESS VARCHAR(20), LOGGED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,USER_ID int, FOREIGN KEY (USER_ID) REFERENCES USER(id));

-- TABLE REGISTERED_DEVICES
CREATE TABLE IF NOT EXISTS REGISTERED_DEVICE( ID int primary key, MACADDRESS VARCHAR(20), DESCRIPTION VARCHAR(200),USER_ID int, FOREIGN KEY (USER_ID) REFERENCES USER(id));
					

-- INSERT DATA
insert into USER(1, 'FREDERIK BYL', CURRENT_TIMESTAMP);